title:             영화 사이트 - 없는거 빼고 다 있음 ㅇㅇ
email:             petyoun000@gmail.com
description:       애니메이션도 있음
author:            지식이
#url:               "localhost:4000"
url:               "https://petyoun000.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
